name: Deploy site files
on:
  push:
    branches:
      - master # 只在 master 上 push 触发部署
jobs:
  deploy:
    runs-on: ubuntu-latest # 使用 ubuntu 系统镜像运行自动化脚本
    strategy:
      matrix:
        node-version: [18.x]
    steps: # 自动化步骤
      - name: Checkout
        uses: actions/checkout@master
      - name: Upload files to deploy server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.SERVER_PORT }}
          source: "./*" # 你要上传的文件或目录
          target: "/home/ubuntu/platform-ai/" # 目标目录
          rm: true
      - name: Deploy on server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            cd /home/ubuntu/platform-ai
            sudo sh deploy.sh
